[package]
name = "config-hound"
version = "0.1.0"
edition = "2021"
authors = ["gxmk9999@gmail.com"]
description = "Enhanced YAML loader"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
